name: SDK Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create local.properties
        uses: finnp/create-file-action@master
        env: {
          FILE_NAME: "local.properties"
#            FILE_DATA: "c2lnbmluZy5rZXlQYXNzd29yZD1hcHBtb25ldApzaWduaW5nLnN0b3JlUGFzc3dvcmQ9YXBwbW9uZXQKc2lnbmluZy5rZXlBbGlhcz1hcHBtb25ldApzaWduaW5nLnN0b3JlRmlsZT1hcHBtb25ldA=="
        }

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Execute unit tests
      - name: SDK Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: SDK Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless